FROM demoweb_base_env:latest

# Run the service.
WORKDIR /home

EXPOSE 8000
EXPOSE 50051

ENV LD_LIBRARY_PATH="./bin/"

CMD ["./bin/demowebmain", \
     "--port=50051", \
     "--demoweb_db_host_name={{postgres_citus_master_location}}", \
     "--demoweb_db_port={{postgres_citus_master_port}}", \
     "--demoweb_db_user_name={{postgres_citus_master_user}}", \
     "--demoweb_db_password={{postgres_citus_master_password}}", \
     "--grpc_web_proxy=true"]

