FROM demoweb_base_env:latest

RUN apt install -y openvpn
RUN apt install -y python3-requests

WORKDIR /home
RUN cp ./demoweb_src/load_balancer/dyn_dns/watch_dog.py ./bin/

WORKDIR /home/bin
CMD ["python3", "watch_dog.py"]
