FROM demoweb_base_env:latest

WORKDIR /home

RUN cp -r ./demoweb_src/client/web_frontend/build/* /var/www/html
RUN cp ./demoweb_src/client/web_frontend/nginx_demoweb_frontend.conf /etc/nginx/sites-available/default

EXPOSE 8080

ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]
