# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nullable_primitives.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nullable_primitives.proto',
  package='e8',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19nullable_primitives.proto\x12\x02\x65\x38\"\x1e\n\rNullableInt32\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1e\n\rNullableInt64\x12\r\n\x05value\x18\x01 \x01(\x03\"\x1e\n\rNullableFloat\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1f\n\x0eNullableDouble\x12\r\n\x05value\x18\x01 \x01(\x01\"\x1f\n\x0eNullableString\x12\r\n\x05value\x18\x01 \x01(\tb\x06proto3')
)




_NULLABLEINT32 = _descriptor.Descriptor(
  name='NullableInt32',
  full_name='e8.NullableInt32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='e8.NullableInt32.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=63,
)


_NULLABLEINT64 = _descriptor.Descriptor(
  name='NullableInt64',
  full_name='e8.NullableInt64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='e8.NullableInt64.value', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=95,
)


_NULLABLEFLOAT = _descriptor.Descriptor(
  name='NullableFloat',
  full_name='e8.NullableFloat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='e8.NullableFloat.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=127,
)


_NULLABLEDOUBLE = _descriptor.Descriptor(
  name='NullableDouble',
  full_name='e8.NullableDouble',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='e8.NullableDouble.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=160,
)


_NULLABLESTRING = _descriptor.Descriptor(
  name='NullableString',
  full_name='e8.NullableString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='e8.NullableString.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=193,
)

DESCRIPTOR.message_types_by_name['NullableInt32'] = _NULLABLEINT32
DESCRIPTOR.message_types_by_name['NullableInt64'] = _NULLABLEINT64
DESCRIPTOR.message_types_by_name['NullableFloat'] = _NULLABLEFLOAT
DESCRIPTOR.message_types_by_name['NullableDouble'] = _NULLABLEDOUBLE
DESCRIPTOR.message_types_by_name['NullableString'] = _NULLABLESTRING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NullableInt32 = _reflection.GeneratedProtocolMessageType('NullableInt32', (_message.Message,), dict(
  DESCRIPTOR = _NULLABLEINT32,
  __module__ = 'nullable_primitives_pb2'
  # @@protoc_insertion_point(class_scope:e8.NullableInt32)
  ))
_sym_db.RegisterMessage(NullableInt32)

NullableInt64 = _reflection.GeneratedProtocolMessageType('NullableInt64', (_message.Message,), dict(
  DESCRIPTOR = _NULLABLEINT64,
  __module__ = 'nullable_primitives_pb2'
  # @@protoc_insertion_point(class_scope:e8.NullableInt64)
  ))
_sym_db.RegisterMessage(NullableInt64)

NullableFloat = _reflection.GeneratedProtocolMessageType('NullableFloat', (_message.Message,), dict(
  DESCRIPTOR = _NULLABLEFLOAT,
  __module__ = 'nullable_primitives_pb2'
  # @@protoc_insertion_point(class_scope:e8.NullableFloat)
  ))
_sym_db.RegisterMessage(NullableFloat)

NullableDouble = _reflection.GeneratedProtocolMessageType('NullableDouble', (_message.Message,), dict(
  DESCRIPTOR = _NULLABLEDOUBLE,
  __module__ = 'nullable_primitives_pb2'
  # @@protoc_insertion_point(class_scope:e8.NullableDouble)
  ))
_sym_db.RegisterMessage(NullableDouble)

NullableString = _reflection.GeneratedProtocolMessageType('NullableString', (_message.Message,), dict(
  DESCRIPTOR = _NULLABLESTRING,
  __module__ = 'nullable_primitives_pb2'
  # @@protoc_insertion_point(class_scope:e8.NullableString)
  ))
_sym_db.RegisterMessage(NullableString)


# @@protoc_insertion_point(module_scope)
