# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_socialnetwork_pb2 as service__socialnetwork__pb2


class SocialNetworkServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetUserRelations = channel.unary_unary(
        '/e8.SocialNetworkService/GetUserRelations',
        request_serializer=service__socialnetwork__pb2.GetUserRelationsRequest.SerializeToString,
        response_deserializer=service__socialnetwork__pb2.GetUserRelationsResponse.FromString,
        )
    self.SendInvitation = channel.unary_unary(
        '/e8.SocialNetworkService/SendInvitation',
        request_serializer=service__socialnetwork__pb2.SendInvitationRequest.SerializeToString,
        response_deserializer=service__socialnetwork__pb2.SendInvitationResponse.FromString,
        )
    self.DeleteInvitation = channel.unary_unary(
        '/e8.SocialNetworkService/DeleteInvitation',
        request_serializer=service__socialnetwork__pb2.DeleteInvitationRequest.SerializeToString,
        response_deserializer=service__socialnetwork__pb2.DeleteInvitationResponse.FromString,
        )
    self.ProcessInvitation = channel.unary_unary(
        '/e8.SocialNetworkService/ProcessInvitation',
        request_serializer=service__socialnetwork__pb2.ProcessInvitationRequest.SerializeToString,
        response_deserializer=service__socialnetwork__pb2.ProcessInvitationResponse.FromString,
        )
    self.DeleteContact = channel.unary_unary(
        '/e8.SocialNetworkService/DeleteContact',
        request_serializer=service__socialnetwork__pb2.DeleteContactRequest.SerializeToString,
        response_deserializer=service__socialnetwork__pb2.DeleteContactResponse.FromString,
        )
    self.GetRelatedUserList = channel.unary_unary(
        '/e8.SocialNetworkService/GetRelatedUserList',
        request_serializer=service__socialnetwork__pb2.GetRelatedUserListRequest.SerializeToString,
        response_deserializer=service__socialnetwork__pb2.GetRelatedUserListResponse.FromString,
        )


class SocialNetworkServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetUserRelations(self, request, context):
    """*
    Get the directed relation between the logged-in user and some other user.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendInvitation(self, request, context):
    """*
    Send an invitation to another user where the logged-in user is the inviter.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteInvitation(self, request, context):
    """*
    Delete an invitation previously sent where the logged-in user is inviter.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProcessInvitation(self, request, context):
    """*
    Accept/reject an invitation. If accepted, it will establish the 
    contact relation where the logged-in user is the invitee.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteContact(self, request, context):
    """*
    Delete a contact relation for the logged-in user.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRelatedUserList(self, request, context):
    """*
    Get the a list of user related to the logged-in user. The type of relation
    is specified by the constraints in the request. 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SocialNetworkServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetUserRelations': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserRelations,
          request_deserializer=service__socialnetwork__pb2.GetUserRelationsRequest.FromString,
          response_serializer=service__socialnetwork__pb2.GetUserRelationsResponse.SerializeToString,
      ),
      'SendInvitation': grpc.unary_unary_rpc_method_handler(
          servicer.SendInvitation,
          request_deserializer=service__socialnetwork__pb2.SendInvitationRequest.FromString,
          response_serializer=service__socialnetwork__pb2.SendInvitationResponse.SerializeToString,
      ),
      'DeleteInvitation': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteInvitation,
          request_deserializer=service__socialnetwork__pb2.DeleteInvitationRequest.FromString,
          response_serializer=service__socialnetwork__pb2.DeleteInvitationResponse.SerializeToString,
      ),
      'ProcessInvitation': grpc.unary_unary_rpc_method_handler(
          servicer.ProcessInvitation,
          request_deserializer=service__socialnetwork__pb2.ProcessInvitationRequest.FromString,
          response_serializer=service__socialnetwork__pb2.ProcessInvitationResponse.SerializeToString,
      ),
      'DeleteContact': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteContact,
          request_deserializer=service__socialnetwork__pb2.DeleteContactRequest.FromString,
          response_serializer=service__socialnetwork__pb2.DeleteContactResponse.SerializeToString,
      ),
      'GetRelatedUserList': grpc.unary_unary_rpc_method_handler(
          servicer.GetRelatedUserList,
          request_deserializer=service__socialnetwork__pb2.GetRelatedUserListRequest.FromString,
          response_serializer=service__socialnetwork__pb2.GetRelatedUserListResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'e8.SocialNetworkService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
