# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_message_channel_pb2 as service__message__channel__pb2


class MessageChannelServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateMessageChannel = channel.unary_unary(
        '/e8.MessageChannelService/CreateMessageChannel',
        request_serializer=service__message__channel__pb2.CreateMessageChannelRequest.SerializeToString,
        response_deserializer=service__message__channel__pb2.CreateMessageChannelResponse.FromString,
        )
    self.AddMemberToMessageChannel = channel.unary_unary(
        '/e8.MessageChannelService/AddMemberToMessageChannel',
        request_serializer=service__message__channel__pb2.AddMemberToMessageChannelRequest.SerializeToString,
        response_deserializer=service__message__channel__pb2.AddMemberToMessageChannelResponse.FromString,
        )
    self.GetMessageChannelKey = channel.unary_unary(
        '/e8.MessageChannelService/GetMessageChannelKey',
        request_serializer=service__message__channel__pb2.GetMessageChannelKeyRequest.SerializeToString,
        response_deserializer=service__message__channel__pb2.GetMessageChannelKeyResponse.FromString,
        )
    self.LeaveMessageChannel = channel.unary_unary(
        '/e8.MessageChannelService/LeaveMessageChannel',
        request_serializer=service__message__channel__pb2.LeaveMessageChannelRequest.SerializeToString,
        response_deserializer=service__message__channel__pb2.LeaveMessageChannelResponse.FromString,
        )
    self.GetJoinedInMessageChannels = channel.unary_unary(
        '/e8.MessageChannelService/GetJoinedInMessageChannels',
        request_serializer=service__message__channel__pb2.GetJoinedInMessageChannelsRequest.SerializeToString,
        response_deserializer=service__message__channel__pb2.GetJoinedInMessageChannelsResponse.FromString,
        )
    self.GetMessageChannelMembers = channel.unary_unary(
        '/e8.MessageChannelService/GetMessageChannelMembers',
        request_serializer=service__message__channel__pb2.GetMessageChannelMembersRequest.SerializeToString,
        response_deserializer=service__message__channel__pb2.GetMessageChannelMembersResponse.FromString,
        )


class MessageChannelServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateMessageChannel(self, request, context):
    """Create a new message channel. The logged-in user will be the 
    administrator of this channel.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddMemberToMessageChannel(self, request, context):
    """Add a member to the specified channel where the logged-in user is the
    administrator.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMessageChannelKey(self, request, context):
    """Get an encryption key of the specified channel where the logged-in
    user is a member.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LeaveMessageChannel(self, request, context):
    """Remove the logged-in user from the specified channel.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetJoinedInMessageChannels(self, request, context):
    """Get a list of channels that the logged-in user is a member of.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMessageChannelMembers(self, request, context):
    """Get information about the members in the specified channel.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessageChannelServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateMessageChannel': grpc.unary_unary_rpc_method_handler(
          servicer.CreateMessageChannel,
          request_deserializer=service__message__channel__pb2.CreateMessageChannelRequest.FromString,
          response_serializer=service__message__channel__pb2.CreateMessageChannelResponse.SerializeToString,
      ),
      'AddMemberToMessageChannel': grpc.unary_unary_rpc_method_handler(
          servicer.AddMemberToMessageChannel,
          request_deserializer=service__message__channel__pb2.AddMemberToMessageChannelRequest.FromString,
          response_serializer=service__message__channel__pb2.AddMemberToMessageChannelResponse.SerializeToString,
      ),
      'GetMessageChannelKey': grpc.unary_unary_rpc_method_handler(
          servicer.GetMessageChannelKey,
          request_deserializer=service__message__channel__pb2.GetMessageChannelKeyRequest.FromString,
          response_serializer=service__message__channel__pb2.GetMessageChannelKeyResponse.SerializeToString,
      ),
      'LeaveMessageChannel': grpc.unary_unary_rpc_method_handler(
          servicer.LeaveMessageChannel,
          request_deserializer=service__message__channel__pb2.LeaveMessageChannelRequest.FromString,
          response_serializer=service__message__channel__pb2.LeaveMessageChannelResponse.SerializeToString,
      ),
      'GetJoinedInMessageChannels': grpc.unary_unary_rpc_method_handler(
          servicer.GetJoinedInMessageChannels,
          request_deserializer=service__message__channel__pb2.GetJoinedInMessageChannelsRequest.FromString,
          response_serializer=service__message__channel__pb2.GetJoinedInMessageChannelsResponse.SerializeToString,
      ),
      'GetMessageChannelMembers': grpc.unary_unary_rpc_method_handler(
          servicer.GetMessageChannelMembers,
          request_deserializer=service__message__channel__pb2.GetMessageChannelMembersRequest.FromString,
          response_serializer=service__message__channel__pb2.GetMessageChannelMembersResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'e8.MessageChannelService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
