// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service_system.proto

#include "service_system.pb.h"
#include "service_system.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace e8 {

static const char* SystemService_method_names[] = {
  "/e8.SystemService/Version",
};

std::unique_ptr< SystemService::Stub> SystemService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SystemService::Stub> stub(new SystemService::Stub(channel));
  return stub;
}

SystemService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Version_(SystemService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SystemService::Stub::Version(::grpc::ClientContext* context, const ::e8::VersionResquest& request, ::e8::VersionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Version_, context, request, response);
}

void SystemService::Stub::experimental_async::Version(::grpc::ClientContext* context, const ::e8::VersionResquest* request, ::e8::VersionResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Version_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::e8::VersionResponse>* SystemService::Stub::AsyncVersionRaw(::grpc::ClientContext* context, const ::e8::VersionResquest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::e8::VersionResponse>::Create(channel_.get(), cq, rpcmethod_Version_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::e8::VersionResponse>* SystemService::Stub::PrepareAsyncVersionRaw(::grpc::ClientContext* context, const ::e8::VersionResquest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::e8::VersionResponse>::Create(channel_.get(), cq, rpcmethod_Version_, context, request, false);
}

SystemService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SystemService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SystemService::Service, ::e8::VersionResquest, ::e8::VersionResponse>(
          std::mem_fn(&SystemService::Service::Version), this)));
}

SystemService::Service::~Service() {
}

::grpc::Status SystemService::Service::Version(::grpc::ServerContext* context, const ::e8::VersionResquest* request, ::e8::VersionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace e8

