FROM demoweb_base_env:latest

# Run the service.
WORKDIR /home

EXPOSE 20021

ENV LD_LIBRARY_PATH="./bin/"

CMD ["./bin/node_state_service_main", \
     "--port=20021", \
     "--sqlite_db_path=/host/home/node_state.sqlite"]
