// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service_file.proto
// Original file comments:
// *
// e8yes demo web server.
//
// <p>Copyright (C) 2020 Chifeng Wen {daviesx66@gmail.com}
//
// <p>This program is free software: you can redistribute it and/or modify it under the terms of the
// GNU General Public License as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// <p>This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// <p>You should have received a copy of the GNU General Public License along with this program. If
// not, see <http://www.gnu.org/licenses/>.
//
#ifndef GRPC_service_5ffile_2eproto__INCLUDED
#define GRPC_service_5ffile_2eproto__INCLUDED

#include "service_file.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace e8 {

class FileService final {
 public:
  static constexpr char const* service_full_name() {
    return "e8.FileService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // *
    // Upload a file.
    std::unique_ptr< ::grpc::ClientWriterInterface< ::e8::UploadFileRequest>> Upload(::grpc::ClientContext* context, ::e8::UploadFileResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::e8::UploadFileRequest>>(UploadRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::e8::UploadFileRequest>> AsyncUpload(::grpc::ClientContext* context, ::e8::UploadFileResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::e8::UploadFileRequest>>(AsyncUploadRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::e8::UploadFileRequest>> PrepareAsyncUpload(::grpc::ClientContext* context, ::e8::UploadFileResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::e8::UploadFileRequest>>(PrepareAsyncUploadRaw(context, response, cq));
    }
    // *
    // Downlaod a file.
    std::unique_ptr< ::grpc::ClientReaderInterface< ::e8::DownloadFileResponse>> Download(::grpc::ClientContext* context, const ::e8::DownloadFileRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::e8::DownloadFileResponse>>(DownloadRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::e8::DownloadFileResponse>> AsyncDownload(::grpc::ClientContext* context, const ::e8::DownloadFileRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::e8::DownloadFileResponse>>(AsyncDownloadRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::e8::DownloadFileResponse>> PrepareAsyncDownload(::grpc::ClientContext* context, const ::e8::DownloadFileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::e8::DownloadFileResponse>>(PrepareAsyncDownloadRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // *
      // Upload a file.
      // *
      // Downlaod a file.
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientWriterInterface< ::e8::UploadFileRequest>* UploadRaw(::grpc::ClientContext* context, ::e8::UploadFileResponse* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::e8::UploadFileRequest>* AsyncUploadRaw(::grpc::ClientContext* context, ::e8::UploadFileResponse* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::e8::UploadFileRequest>* PrepareAsyncUploadRaw(::grpc::ClientContext* context, ::e8::UploadFileResponse* response, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::e8::DownloadFileResponse>* DownloadRaw(::grpc::ClientContext* context, const ::e8::DownloadFileRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::e8::DownloadFileResponse>* AsyncDownloadRaw(::grpc::ClientContext* context, const ::e8::DownloadFileRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::e8::DownloadFileResponse>* PrepareAsyncDownloadRaw(::grpc::ClientContext* context, const ::e8::DownloadFileRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientWriter< ::e8::UploadFileRequest>> Upload(::grpc::ClientContext* context, ::e8::UploadFileResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::e8::UploadFileRequest>>(UploadRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::e8::UploadFileRequest>> AsyncUpload(::grpc::ClientContext* context, ::e8::UploadFileResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::e8::UploadFileRequest>>(AsyncUploadRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::e8::UploadFileRequest>> PrepareAsyncUpload(::grpc::ClientContext* context, ::e8::UploadFileResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::e8::UploadFileRequest>>(PrepareAsyncUploadRaw(context, response, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::e8::DownloadFileResponse>> Download(::grpc::ClientContext* context, const ::e8::DownloadFileRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::e8::DownloadFileResponse>>(DownloadRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::e8::DownloadFileResponse>> AsyncDownload(::grpc::ClientContext* context, const ::e8::DownloadFileRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::e8::DownloadFileResponse>>(AsyncDownloadRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::e8::DownloadFileResponse>> PrepareAsyncDownload(::grpc::ClientContext* context, const ::e8::DownloadFileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::e8::DownloadFileResponse>>(PrepareAsyncDownloadRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientWriter< ::e8::UploadFileRequest>* UploadRaw(::grpc::ClientContext* context, ::e8::UploadFileResponse* response) override;
    ::grpc::ClientAsyncWriter< ::e8::UploadFileRequest>* AsyncUploadRaw(::grpc::ClientContext* context, ::e8::UploadFileResponse* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::e8::UploadFileRequest>* PrepareAsyncUploadRaw(::grpc::ClientContext* context, ::e8::UploadFileResponse* response, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::e8::DownloadFileResponse>* DownloadRaw(::grpc::ClientContext* context, const ::e8::DownloadFileRequest& request) override;
    ::grpc::ClientAsyncReader< ::e8::DownloadFileResponse>* AsyncDownloadRaw(::grpc::ClientContext* context, const ::e8::DownloadFileRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::e8::DownloadFileResponse>* PrepareAsyncDownloadRaw(::grpc::ClientContext* context, const ::e8::DownloadFileRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Upload_;
    const ::grpc::internal::RpcMethod rpcmethod_Download_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // *
    // Upload a file.
    virtual ::grpc::Status Upload(::grpc::ServerContext* context, ::grpc::ServerReader< ::e8::UploadFileRequest>* reader, ::e8::UploadFileResponse* response);
    // *
    // Downlaod a file.
    virtual ::grpc::Status Download(::grpc::ServerContext* context, const ::e8::DownloadFileRequest* request, ::grpc::ServerWriter< ::e8::DownloadFileResponse>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_Upload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Upload() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Upload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Upload(::grpc::ServerContext* context, ::grpc::ServerReader< ::e8::UploadFileRequest>* reader, ::e8::UploadFileResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpload(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::e8::UploadFileResponse, ::e8::UploadFileRequest>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Download : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Download() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Download() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Download(::grpc::ServerContext* context, const ::e8::DownloadFileRequest* request, ::grpc::ServerWriter< ::e8::DownloadFileResponse>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDownload(::grpc::ServerContext* context, ::e8::DownloadFileRequest* request, ::grpc::ServerAsyncWriter< ::e8::DownloadFileResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Upload<WithAsyncMethod_Download<Service > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Upload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Upload() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Upload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Upload(::grpc::ServerContext* context, ::grpc::ServerReader< ::e8::UploadFileRequest>* reader, ::e8::UploadFileResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Download : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Download() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Download() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Download(::grpc::ServerContext* context, const ::e8::DownloadFileRequest* request, ::grpc::ServerWriter< ::e8::DownloadFileResponse>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Upload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Upload() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Upload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Upload(::grpc::ServerContext* context, ::grpc::ServerReader< ::e8::UploadFileRequest>* reader, ::e8::UploadFileResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpload(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Download : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Download() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Download() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Download(::grpc::ServerContext* context, const ::e8::DownloadFileRequest* request, ::grpc::ServerWriter< ::e8::DownloadFileResponse>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDownload(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_Download : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithSplitStreamingMethod_Download() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler< ::e8::DownloadFileRequest, ::e8::DownloadFileResponse>(std::bind(&WithSplitStreamingMethod_Download<BaseClass>::StreamedDownload, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithSplitStreamingMethod_Download() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Download(::grpc::ServerContext* context, const ::e8::DownloadFileRequest* request, ::grpc::ServerWriter< ::e8::DownloadFileResponse>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedDownload(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::e8::DownloadFileRequest,::e8::DownloadFileResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_Download<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_Download<Service > StreamedService;
};

}  // namespace e8


#endif  // GRPC_service_5ffile_2eproto__INCLUDED
