// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_queue_stats.proto

#ifndef PROTOBUF_INCLUDED_message_5fqueue_5fstats_2eproto
#define PROTOBUF_INCLUDED_message_5fqueue_5fstats_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_message_5fqueue_5fstats_2eproto 

namespace protobuf_message_5fqueue_5fstats_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_message_5fqueue_5fstats_2eproto
namespace e8 {
class MessageQueueStats;
class MessageQueueStatsDefaultTypeInternal;
extern MessageQueueStatsDefaultTypeInternal _MessageQueueStats_default_instance_;
}  // namespace e8
namespace google {
namespace protobuf {
template<> ::e8::MessageQueueStats* Arena::CreateMaybeMessage<::e8::MessageQueueStats>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace e8 {

// ===================================================================

class MessageQueueStats : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:e8.MessageQueueStats) */ {
 public:
  MessageQueueStats();
  virtual ~MessageQueueStats();

  MessageQueueStats(const MessageQueueStats& from);

  inline MessageQueueStats& operator=(const MessageQueueStats& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MessageQueueStats(MessageQueueStats&& from) noexcept
    : MessageQueueStats() {
    *this = ::std::move(from);
  }

  inline MessageQueueStats& operator=(MessageQueueStats&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageQueueStats& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MessageQueueStats* internal_default_instance() {
    return reinterpret_cast<const MessageQueueStats*>(
               &_MessageQueueStats_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(MessageQueueStats* other);
  friend void swap(MessageQueueStats& a, MessageQueueStats& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MessageQueueStats* New() const final {
    return CreateMaybeMessage<MessageQueueStats>(NULL);
  }

  MessageQueueStats* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MessageQueueStats>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MessageQueueStats& from);
  void MergeFrom(const MessageQueueStats& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MessageQueueStats* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 total_num_queues = 1;
  void clear_total_num_queues();
  static const int kTotalNumQueuesFieldNumber = 1;
  ::google::protobuf::int32 total_num_queues() const;
  void set_total_num_queues(::google::protobuf::int32 value);

  // int32 num_queues_length_0 = 2;
  void clear_num_queues_length_0();
  static const int kNumQueuesLength0FieldNumber = 2;
  ::google::protobuf::int32 num_queues_length_0() const;
  void set_num_queues_length_0(::google::protobuf::int32 value);

  // int32 num_queues_length_1_10 = 3;
  void clear_num_queues_length_1_10();
  static const int kNumQueuesLength110FieldNumber = 3;
  ::google::protobuf::int32 num_queues_length_1_10() const;
  void set_num_queues_length_1_10(::google::protobuf::int32 value);

  // int32 num_queues_length_11_100 = 4;
  void clear_num_queues_length_11_100();
  static const int kNumQueuesLength11100FieldNumber = 4;
  ::google::protobuf::int32 num_queues_length_11_100() const;
  void set_num_queues_length_11_100(::google::protobuf::int32 value);

  // int32 num_queues_length_101_1000 = 5;
  void clear_num_queues_length_101_1000();
  static const int kNumQueuesLength1011000FieldNumber = 5;
  ::google::protobuf::int32 num_queues_length_101_1000() const;
  void set_num_queues_length_101_1000(::google::protobuf::int32 value);

  // int32 num_queues_length_gte_1001 = 6;
  void clear_num_queues_length_gte_1001();
  static const int kNumQueuesLengthGte1001FieldNumber = 6;
  ::google::protobuf::int32 num_queues_length_gte_1001() const;
  void set_num_queues_length_gte_1001(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:e8.MessageQueueStats)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 total_num_queues_;
  ::google::protobuf::int32 num_queues_length_0_;
  ::google::protobuf::int32 num_queues_length_1_10_;
  ::google::protobuf::int32 num_queues_length_11_100_;
  ::google::protobuf::int32 num_queues_length_101_1000_;
  ::google::protobuf::int32 num_queues_length_gte_1001_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_message_5fqueue_5fstats_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MessageQueueStats

// int32 total_num_queues = 1;
inline void MessageQueueStats::clear_total_num_queues() {
  total_num_queues_ = 0;
}
inline ::google::protobuf::int32 MessageQueueStats::total_num_queues() const {
  // @@protoc_insertion_point(field_get:e8.MessageQueueStats.total_num_queues)
  return total_num_queues_;
}
inline void MessageQueueStats::set_total_num_queues(::google::protobuf::int32 value) {
  
  total_num_queues_ = value;
  // @@protoc_insertion_point(field_set:e8.MessageQueueStats.total_num_queues)
}

// int32 num_queues_length_0 = 2;
inline void MessageQueueStats::clear_num_queues_length_0() {
  num_queues_length_0_ = 0;
}
inline ::google::protobuf::int32 MessageQueueStats::num_queues_length_0() const {
  // @@protoc_insertion_point(field_get:e8.MessageQueueStats.num_queues_length_0)
  return num_queues_length_0_;
}
inline void MessageQueueStats::set_num_queues_length_0(::google::protobuf::int32 value) {
  
  num_queues_length_0_ = value;
  // @@protoc_insertion_point(field_set:e8.MessageQueueStats.num_queues_length_0)
}

// int32 num_queues_length_1_10 = 3;
inline void MessageQueueStats::clear_num_queues_length_1_10() {
  num_queues_length_1_10_ = 0;
}
inline ::google::protobuf::int32 MessageQueueStats::num_queues_length_1_10() const {
  // @@protoc_insertion_point(field_get:e8.MessageQueueStats.num_queues_length_1_10)
  return num_queues_length_1_10_;
}
inline void MessageQueueStats::set_num_queues_length_1_10(::google::protobuf::int32 value) {
  
  num_queues_length_1_10_ = value;
  // @@protoc_insertion_point(field_set:e8.MessageQueueStats.num_queues_length_1_10)
}

// int32 num_queues_length_11_100 = 4;
inline void MessageQueueStats::clear_num_queues_length_11_100() {
  num_queues_length_11_100_ = 0;
}
inline ::google::protobuf::int32 MessageQueueStats::num_queues_length_11_100() const {
  // @@protoc_insertion_point(field_get:e8.MessageQueueStats.num_queues_length_11_100)
  return num_queues_length_11_100_;
}
inline void MessageQueueStats::set_num_queues_length_11_100(::google::protobuf::int32 value) {
  
  num_queues_length_11_100_ = value;
  // @@protoc_insertion_point(field_set:e8.MessageQueueStats.num_queues_length_11_100)
}

// int32 num_queues_length_101_1000 = 5;
inline void MessageQueueStats::clear_num_queues_length_101_1000() {
  num_queues_length_101_1000_ = 0;
}
inline ::google::protobuf::int32 MessageQueueStats::num_queues_length_101_1000() const {
  // @@protoc_insertion_point(field_get:e8.MessageQueueStats.num_queues_length_101_1000)
  return num_queues_length_101_1000_;
}
inline void MessageQueueStats::set_num_queues_length_101_1000(::google::protobuf::int32 value) {
  
  num_queues_length_101_1000_ = value;
  // @@protoc_insertion_point(field_set:e8.MessageQueueStats.num_queues_length_101_1000)
}

// int32 num_queues_length_gte_1001 = 6;
inline void MessageQueueStats::clear_num_queues_length_gte_1001() {
  num_queues_length_gte_1001_ = 0;
}
inline ::google::protobuf::int32 MessageQueueStats::num_queues_length_gte_1001() const {
  // @@protoc_insertion_point(field_get:e8.MessageQueueStats.num_queues_length_gte_1001)
  return num_queues_length_gte_1001_;
}
inline void MessageQueueStats::set_num_queues_length_gte_1001(::google::protobuf::int32 value) {
  
  num_queues_length_gte_1001_ = value;
  // @@protoc_insertion_point(field_set:e8.MessageQueueStats.num_queues_length_gte_1001)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace e8

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_message_5fqueue_5fstats_2eproto
