// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nullable_primitives.proto

#include "nullable_primitives.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace e8 {
class NullableInt32DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NullableInt32>
      _instance;
} _NullableInt32_default_instance_;
class NullableInt64DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NullableInt64>
      _instance;
} _NullableInt64_default_instance_;
class NullableFloatDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NullableFloat>
      _instance;
} _NullableFloat_default_instance_;
class NullableDoubleDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NullableDouble>
      _instance;
} _NullableDouble_default_instance_;
class NullableStringDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NullableString>
      _instance;
} _NullableString_default_instance_;
}  // namespace e8
namespace protobuf_nullable_5fprimitives_2eproto {
static void InitDefaultsNullableInt32() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::e8::_NullableInt32_default_instance_;
    new (ptr) ::e8::NullableInt32();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::e8::NullableInt32::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_NullableInt32 =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsNullableInt32}, {}};

static void InitDefaultsNullableInt64() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::e8::_NullableInt64_default_instance_;
    new (ptr) ::e8::NullableInt64();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::e8::NullableInt64::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_NullableInt64 =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsNullableInt64}, {}};

static void InitDefaultsNullableFloat() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::e8::_NullableFloat_default_instance_;
    new (ptr) ::e8::NullableFloat();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::e8::NullableFloat::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_NullableFloat =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsNullableFloat}, {}};

static void InitDefaultsNullableDouble() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::e8::_NullableDouble_default_instance_;
    new (ptr) ::e8::NullableDouble();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::e8::NullableDouble::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_NullableDouble =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsNullableDouble}, {}};

static void InitDefaultsNullableString() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::e8::_NullableString_default_instance_;
    new (ptr) ::e8::NullableString();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::e8::NullableString::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_NullableString =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsNullableString}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_NullableInt32.base);
  ::google::protobuf::internal::InitSCC(&scc_info_NullableInt64.base);
  ::google::protobuf::internal::InitSCC(&scc_info_NullableFloat.base);
  ::google::protobuf::internal::InitSCC(&scc_info_NullableDouble.base);
  ::google::protobuf::internal::InitSCC(&scc_info_NullableString.base);
}

::google::protobuf::Metadata file_level_metadata[5];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::e8::NullableInt32, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::e8::NullableInt32, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::e8::NullableInt64, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::e8::NullableInt64, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::e8::NullableFloat, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::e8::NullableFloat, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::e8::NullableDouble, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::e8::NullableDouble, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::e8::NullableString, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::e8::NullableString, value_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::e8::NullableInt32)},
  { 6, -1, sizeof(::e8::NullableInt64)},
  { 12, -1, sizeof(::e8::NullableFloat)},
  { 18, -1, sizeof(::e8::NullableDouble)},
  { 24, -1, sizeof(::e8::NullableString)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::e8::_NullableInt32_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::e8::_NullableInt64_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::e8::_NullableFloat_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::e8::_NullableDouble_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::e8::_NullableString_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "nullable_primitives.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\031nullable_primitives.proto\022\002e8\"\036\n\rNulla"
      "bleInt32\022\r\n\005value\030\001 \001(\005\"\036\n\rNullableInt64"
      "\022\r\n\005value\030\001 \001(\003\"\036\n\rNullableFloat\022\r\n\005valu"
      "e\030\001 \001(\002\"\037\n\016NullableDouble\022\r\n\005value\030\001 \001(\001"
      "\"\037\n\016NullableString\022\r\n\005value\030\001 \001(\tb\006proto"
      "3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 201);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "nullable_primitives.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_nullable_5fprimitives_2eproto
namespace e8 {

// ===================================================================

void NullableInt32::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NullableInt32::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NullableInt32::NullableInt32()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_nullable_5fprimitives_2eproto::scc_info_NullableInt32.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:e8.NullableInt32)
}
NullableInt32::NullableInt32(const NullableInt32& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  value_ = from.value_;
  // @@protoc_insertion_point(copy_constructor:e8.NullableInt32)
}

void NullableInt32::SharedCtor() {
  value_ = 0;
}

NullableInt32::~NullableInt32() {
  // @@protoc_insertion_point(destructor:e8.NullableInt32)
  SharedDtor();
}

void NullableInt32::SharedDtor() {
}

void NullableInt32::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* NullableInt32::descriptor() {
  ::protobuf_nullable_5fprimitives_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_nullable_5fprimitives_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NullableInt32& NullableInt32::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_nullable_5fprimitives_2eproto::scc_info_NullableInt32.base);
  return *internal_default_instance();
}


void NullableInt32::Clear() {
// @@protoc_insertion_point(message_clear_start:e8.NullableInt32)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  value_ = 0;
  _internal_metadata_.Clear();
}

bool NullableInt32::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:e8.NullableInt32)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 value = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:e8.NullableInt32)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:e8.NullableInt32)
  return false;
#undef DO_
}

void NullableInt32::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:e8.NullableInt32)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 value = 1;
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:e8.NullableInt32)
}

::google::protobuf::uint8* NullableInt32::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:e8.NullableInt32)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 value = 1;
  if (this->value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:e8.NullableInt32)
  return target;
}

size_t NullableInt32::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:e8.NullableInt32)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 value = 1;
  if (this->value() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NullableInt32::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:e8.NullableInt32)
  GOOGLE_DCHECK_NE(&from, this);
  const NullableInt32* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NullableInt32>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:e8.NullableInt32)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:e8.NullableInt32)
    MergeFrom(*source);
  }
}

void NullableInt32::MergeFrom(const NullableInt32& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:e8.NullableInt32)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.value() != 0) {
    set_value(from.value());
  }
}

void NullableInt32::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:e8.NullableInt32)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NullableInt32::CopyFrom(const NullableInt32& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:e8.NullableInt32)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NullableInt32::IsInitialized() const {
  return true;
}

void NullableInt32::Swap(NullableInt32* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NullableInt32::InternalSwap(NullableInt32* other) {
  using std::swap;
  swap(value_, other->value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata NullableInt32::GetMetadata() const {
  protobuf_nullable_5fprimitives_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_nullable_5fprimitives_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void NullableInt64::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NullableInt64::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NullableInt64::NullableInt64()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_nullable_5fprimitives_2eproto::scc_info_NullableInt64.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:e8.NullableInt64)
}
NullableInt64::NullableInt64(const NullableInt64& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  value_ = from.value_;
  // @@protoc_insertion_point(copy_constructor:e8.NullableInt64)
}

void NullableInt64::SharedCtor() {
  value_ = GOOGLE_LONGLONG(0);
}

NullableInt64::~NullableInt64() {
  // @@protoc_insertion_point(destructor:e8.NullableInt64)
  SharedDtor();
}

void NullableInt64::SharedDtor() {
}

void NullableInt64::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* NullableInt64::descriptor() {
  ::protobuf_nullable_5fprimitives_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_nullable_5fprimitives_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NullableInt64& NullableInt64::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_nullable_5fprimitives_2eproto::scc_info_NullableInt64.base);
  return *internal_default_instance();
}


void NullableInt64::Clear() {
// @@protoc_insertion_point(message_clear_start:e8.NullableInt64)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  value_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool NullableInt64::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:e8.NullableInt64)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 value = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:e8.NullableInt64)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:e8.NullableInt64)
  return false;
#undef DO_
}

void NullableInt64::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:e8.NullableInt64)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 value = 1;
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:e8.NullableInt64)
}

::google::protobuf::uint8* NullableInt64::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:e8.NullableInt64)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 value = 1;
  if (this->value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:e8.NullableInt64)
  return target;
}

size_t NullableInt64::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:e8.NullableInt64)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int64 value = 1;
  if (this->value() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NullableInt64::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:e8.NullableInt64)
  GOOGLE_DCHECK_NE(&from, this);
  const NullableInt64* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NullableInt64>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:e8.NullableInt64)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:e8.NullableInt64)
    MergeFrom(*source);
  }
}

void NullableInt64::MergeFrom(const NullableInt64& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:e8.NullableInt64)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.value() != 0) {
    set_value(from.value());
  }
}

void NullableInt64::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:e8.NullableInt64)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NullableInt64::CopyFrom(const NullableInt64& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:e8.NullableInt64)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NullableInt64::IsInitialized() const {
  return true;
}

void NullableInt64::Swap(NullableInt64* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NullableInt64::InternalSwap(NullableInt64* other) {
  using std::swap;
  swap(value_, other->value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata NullableInt64::GetMetadata() const {
  protobuf_nullable_5fprimitives_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_nullable_5fprimitives_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void NullableFloat::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NullableFloat::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NullableFloat::NullableFloat()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_nullable_5fprimitives_2eproto::scc_info_NullableFloat.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:e8.NullableFloat)
}
NullableFloat::NullableFloat(const NullableFloat& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  value_ = from.value_;
  // @@protoc_insertion_point(copy_constructor:e8.NullableFloat)
}

void NullableFloat::SharedCtor() {
  value_ = 0;
}

NullableFloat::~NullableFloat() {
  // @@protoc_insertion_point(destructor:e8.NullableFloat)
  SharedDtor();
}

void NullableFloat::SharedDtor() {
}

void NullableFloat::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* NullableFloat::descriptor() {
  ::protobuf_nullable_5fprimitives_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_nullable_5fprimitives_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NullableFloat& NullableFloat::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_nullable_5fprimitives_2eproto::scc_info_NullableFloat.base);
  return *internal_default_instance();
}


void NullableFloat::Clear() {
// @@protoc_insertion_point(message_clear_start:e8.NullableFloat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  value_ = 0;
  _internal_metadata_.Clear();
}

bool NullableFloat::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:e8.NullableFloat)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float value = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:e8.NullableFloat)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:e8.NullableFloat)
  return false;
#undef DO_
}

void NullableFloat::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:e8.NullableFloat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float value = 1;
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:e8.NullableFloat)
}

::google::protobuf::uint8* NullableFloat::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:e8.NullableFloat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float value = 1;
  if (this->value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:e8.NullableFloat)
  return target;
}

size_t NullableFloat::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:e8.NullableFloat)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // float value = 1;
  if (this->value() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NullableFloat::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:e8.NullableFloat)
  GOOGLE_DCHECK_NE(&from, this);
  const NullableFloat* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NullableFloat>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:e8.NullableFloat)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:e8.NullableFloat)
    MergeFrom(*source);
  }
}

void NullableFloat::MergeFrom(const NullableFloat& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:e8.NullableFloat)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.value() != 0) {
    set_value(from.value());
  }
}

void NullableFloat::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:e8.NullableFloat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NullableFloat::CopyFrom(const NullableFloat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:e8.NullableFloat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NullableFloat::IsInitialized() const {
  return true;
}

void NullableFloat::Swap(NullableFloat* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NullableFloat::InternalSwap(NullableFloat* other) {
  using std::swap;
  swap(value_, other->value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata NullableFloat::GetMetadata() const {
  protobuf_nullable_5fprimitives_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_nullable_5fprimitives_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void NullableDouble::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NullableDouble::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NullableDouble::NullableDouble()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_nullable_5fprimitives_2eproto::scc_info_NullableDouble.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:e8.NullableDouble)
}
NullableDouble::NullableDouble(const NullableDouble& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  value_ = from.value_;
  // @@protoc_insertion_point(copy_constructor:e8.NullableDouble)
}

void NullableDouble::SharedCtor() {
  value_ = 0;
}

NullableDouble::~NullableDouble() {
  // @@protoc_insertion_point(destructor:e8.NullableDouble)
  SharedDtor();
}

void NullableDouble::SharedDtor() {
}

void NullableDouble::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* NullableDouble::descriptor() {
  ::protobuf_nullable_5fprimitives_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_nullable_5fprimitives_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NullableDouble& NullableDouble::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_nullable_5fprimitives_2eproto::scc_info_NullableDouble.base);
  return *internal_default_instance();
}


void NullableDouble::Clear() {
// @@protoc_insertion_point(message_clear_start:e8.NullableDouble)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  value_ = 0;
  _internal_metadata_.Clear();
}

bool NullableDouble::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:e8.NullableDouble)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double value = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:e8.NullableDouble)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:e8.NullableDouble)
  return false;
#undef DO_
}

void NullableDouble::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:e8.NullableDouble)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double value = 1;
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:e8.NullableDouble)
}

::google::protobuf::uint8* NullableDouble::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:e8.NullableDouble)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double value = 1;
  if (this->value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:e8.NullableDouble)
  return target;
}

size_t NullableDouble::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:e8.NullableDouble)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // double value = 1;
  if (this->value() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NullableDouble::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:e8.NullableDouble)
  GOOGLE_DCHECK_NE(&from, this);
  const NullableDouble* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NullableDouble>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:e8.NullableDouble)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:e8.NullableDouble)
    MergeFrom(*source);
  }
}

void NullableDouble::MergeFrom(const NullableDouble& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:e8.NullableDouble)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.value() != 0) {
    set_value(from.value());
  }
}

void NullableDouble::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:e8.NullableDouble)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NullableDouble::CopyFrom(const NullableDouble& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:e8.NullableDouble)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NullableDouble::IsInitialized() const {
  return true;
}

void NullableDouble::Swap(NullableDouble* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NullableDouble::InternalSwap(NullableDouble* other) {
  using std::swap;
  swap(value_, other->value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata NullableDouble::GetMetadata() const {
  protobuf_nullable_5fprimitives_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_nullable_5fprimitives_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void NullableString::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NullableString::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NullableString::NullableString()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_nullable_5fprimitives_2eproto::scc_info_NullableString.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:e8.NullableString)
}
NullableString::NullableString(const NullableString& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.value().size() > 0) {
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  // @@protoc_insertion_point(copy_constructor:e8.NullableString)
}

void NullableString::SharedCtor() {
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

NullableString::~NullableString() {
  // @@protoc_insertion_point(destructor:e8.NullableString)
  SharedDtor();
}

void NullableString::SharedDtor() {
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void NullableString::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* NullableString::descriptor() {
  ::protobuf_nullable_5fprimitives_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_nullable_5fprimitives_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NullableString& NullableString::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_nullable_5fprimitives_2eproto::scc_info_NullableString.base);
  return *internal_default_instance();
}


void NullableString::Clear() {
// @@protoc_insertion_point(message_clear_start:e8.NullableString)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool NullableString::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:e8.NullableString)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string value = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value().data(), static_cast<int>(this->value().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "e8.NullableString.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:e8.NullableString)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:e8.NullableString)
  return false;
#undef DO_
}

void NullableString::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:e8.NullableString)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string value = 1;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), static_cast<int>(this->value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "e8.NullableString.value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:e8.NullableString)
}

::google::protobuf::uint8* NullableString::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:e8.NullableString)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string value = 1;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), static_cast<int>(this->value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "e8.NullableString.value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:e8.NullableString)
  return target;
}

size_t NullableString::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:e8.NullableString)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string value = 1;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NullableString::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:e8.NullableString)
  GOOGLE_DCHECK_NE(&from, this);
  const NullableString* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NullableString>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:e8.NullableString)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:e8.NullableString)
    MergeFrom(*source);
  }
}

void NullableString::MergeFrom(const NullableString& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:e8.NullableString)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.value().size() > 0) {

    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
}

void NullableString::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:e8.NullableString)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NullableString::CopyFrom(const NullableString& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:e8.NullableString)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NullableString::IsInitialized() const {
  return true;
}

void NullableString::Swap(NullableString* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NullableString::InternalSwap(NullableString* other) {
  using std::swap;
  value_.Swap(&other->value_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata NullableString::GetMetadata() const {
  protobuf_nullable_5fprimitives_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_nullable_5fprimitives_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace e8
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::e8::NullableInt32* Arena::CreateMaybeMessage< ::e8::NullableInt32 >(Arena* arena) {
  return Arena::CreateInternal< ::e8::NullableInt32 >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::e8::NullableInt64* Arena::CreateMaybeMessage< ::e8::NullableInt64 >(Arena* arena) {
  return Arena::CreateInternal< ::e8::NullableInt64 >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::e8::NullableFloat* Arena::CreateMaybeMessage< ::e8::NullableFloat >(Arena* arena) {
  return Arena::CreateInternal< ::e8::NullableFloat >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::e8::NullableDouble* Arena::CreateMaybeMessage< ::e8::NullableDouble >(Arena* arena) {
  return Arena::CreateInternal< ::e8::NullableDouble >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::e8::NullableString* Arena::CreateMaybeMessage< ::e8::NullableString >(Arena* arena) {
  return Arena::CreateInternal< ::e8::NullableString >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
